# Generated by Django 4.2.1 on 2023-05-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_alter_answer_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Javob", "verbose_name_plural": "Javoblar"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="examp",
            options={"verbose_name": "Imtihon", "verbose_name_plural": "Imtihonlar"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Savol", "verbose_name_plural": "Savollar"},
        ),
        migrations.AlterModelOptions(
            name="result",
            options={"verbose_name": "Natija", "verbose_name_plural": "Natijalar"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Kichik kategoriya",
                "verbose_name_plural": "Kichik kategoriyalar",
            },
        ),
        migrations.AddField(
            model_name="result",
            name="answers",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
