# Generated by Django 4.2.1 on 2023-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0007_freeresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Batafsil"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="examp_type",
            field=models.CharField(
                choices=[
                    ("free", "Ochiq imtihonlar"),
                    ("always", "Doimiy imtihonlar"),
                    ("dayly", "Kunlik imtihonlar"),
                    ("weekly", "Haftalik imtihonlar"),
                    ("monthly", "Oylik imtihonlar"),
                ],
                default="always",
                max_length=20,
                verbose_name="Imtihon turi",
            ),
        ),
        migrations.AlterField(
            model_name="examp",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Batafsil"),
        ),
    ]
