# Generated by Django 4.2.1 on 2023-05-22 11:40

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_file_slug_mycourse_slug"),
        ("exam", "0008_subcategory_about_subcategory_examp_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1,
                editable=False,
                populate_from=exam.models.slug_funckion_for_answer_model,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="freeresult",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1,
                editable=False,
                populate_from=exam.models.slug_funckion_for_free_result_model,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1,
                editable=False,
                populate_from=exam.models.slug_funckion_for_question_model,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="result",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1,
                editable=False,
                populate_from=exam.models.slug_funckion_for_result_model,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subcategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="examp",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examp",
                to="course.lessons",
            ),
        ),
    ]
