# Generated by Django 4.2.1 on 2023-05-24 03:36

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0009_answer_slug_category_slug_freeresult_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ochiq Kategoriya",
                "verbose_name_plural": "Ochiq Kategoriyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="freeresult",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Ochiq Natija",
                "verbose_name_plural": "Ochiq Natijalar",
            },
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="examp_type",
            field=models.CharField(
                choices=[
                    ("always", "Doimiy imtihonlar"),
                    ("dayly", "Kunlik imtihonlar"),
                    ("weekly", "Haftalik imtihonlar"),
                    ("monthly", "Oylik imtihonlar"),
                ],
                default="always",
                max_length=20,
                verbose_name="Imtihon turi",
            ),
        ),
        migrations.CreateModel(
            name="FreeSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Batafsil"),
                ),
                (
                    "examp_type",
                    models.CharField(
                        choices=[
                            ("always", "Doimiy imtihonlar"),
                            ("dayly", "Kunlik imtihonlar"),
                            ("weekly", "Haftalik imtihonlar"),
                            ("monthly", "Oylik imtihonlar"),
                        ],
                        default="always",
                        max_length=20,
                        verbose_name="Imtihon turi",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_subcategories",
                        to="exam.freecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ochiq Kichik kategoriya",
                "verbose_name_plural": "Ochiq Kichik kategoriyalar",
            },
        ),
        migrations.AlterField(
            model_name="freeresult",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="free_results",
                to="exam.freesubcategory",
            ),
        ),
    ]
