# Generated by Django 4.2.1 on 2023-05-24 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0010_freecategory_alter_freeresult_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="free_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exam.freesubcategory",
            ),
        ),
    ]
