# Generated by Django 4.2.1 on 2023-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
