# Generated by Django 4.2.1 on 2023-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_lessons_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
