# Generated by Django 4.2.1 on 2023-05-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_lessons_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurslar",
            },
        ),
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "Fayl", "verbose_name_plural": "Fayllar"},
        ),
        migrations.AlterModelOptions(
            name="lessons",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Dars",
                "verbose_name_plural": "Darslar",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "O'qtuvchi",
                "verbose_name_plural": "O'qtuvchilar",
            },
        ),
    ]
