# Generated by Django 4.2.1 on 2023-05-22 11:21

import autoslug.fields
import course.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_mycourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1,
                editable=False,
                populate_from=course.models.slug_funckion_for_file_model,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mycourse",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1,
                editable=False,
                populate_from=course.models.slug_funckion_for_mycourse_model,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
    ]
