# Generated by Django 4.2.1 on 2023-05-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_file_slug_mycourse_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_photo/%Y/%m/%d/"
            ),
        ),
    ]
