# Generated by Django 4.2.1 on 2023-05-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_course_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="about",
            field=models.TextField(verbose_name="dars haqida"),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="body",
            field=models.TextField(blank=True, null=True, verbose_name="Dars matni"),
        ),
    ]
