# Generated by Django 4.2.1 on 2023-05-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_course_about_alter_lessons_about_alter_lessons_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessons",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Dars",
                "verbose_name_plural": "Darslar",
            },
        ),
        migrations.AddField(
            model_name="mycourse",
            name="next_lesson",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
