# Generated by Django 4.2.1 on 2023-05-24 11:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_alter_lessons_options_mycourse_next_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessons",
            name="course",
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=111, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bo'lim",
                "verbose_name_plural": "Bo'limlar",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddField(
            model_name="lessons",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="course.unit",
            ),
            preserve_default=False,
        ),
    ]
