# Generated by Django 4.2.1 on 2023-05-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_remove_lessons_course_unit_lessons_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="course.course",
            ),
        ),
    ]
