# Generated by Django 4.2.1 on 2023-05-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="student",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="student",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
