# Generated by Django 4.2.1 on 2023-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_managers_remove_student_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("man", "Erkak"), ("woman", "Ayol")],
                default="man",
                max_length=10,
                verbose_name="Jinsi",
            ),
        ),
    ]
