# Generated by Django 4.2.1 on 2023-05-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_remove_student_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Tel. raqam"),
        ),
    ]
