# Generated by Django 4.2.1 on 2023-05-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_mycourse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mycourse",
            options={
                "verbose_name": "Mening kursim",
                "verbose_name_plural": "Mening kurslarim",
            },
        ),
    ]
