# Generated by Django 4.2.1 on 2023-05-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_alter_mycourse_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=250)),
                ("comment", models.TextField()),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar",
                "ordering": ("-created_at",),
            },
        ),
    ]
