# Generated by Django 4.2.1 on 2023-05-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyCourse",
        ),
    ]
